// Loads OpenCV.js lazily (on first "Run detection" click, not on page load —
// @techstark/opencv-js's bundle is ~13MB) and caches the readiness promise
// so every caller in one session shares the same loaded instance.
//
// Confirmed by inspecting the installed package directly: its WASM binary is
// already inlined in the JS (`findWasmBinary()` returns a decoded literal,
// not a separate fetch) — so once this promise resolves, there is no further
// network activity, which is what makes this satisfy the "no cloud
// dependency" requirement for the CV half of the pipeline. Tesseract.js
// (ocrWorker.ts) is the one that needs local static-asset wiring instead,
// since its worker/core/language files are genuinely separate fetches.
//
// The readiness contract below is exactly what the package's own README
// documents: the default export can already be a Promise, an
// already-initialized module (has `.Mat`), or a not-yet-initialized module
// that still needs `onRuntimeInitialized` to fire. Which one you get differs
// by version, so all three are handled rather than assuming one.
//
// Typed as `any` throughout (not just here) — the package's own README
// acknowledges its shipped .d.ts (auto-generated by a third-party tool,
// "mirada") lags the real OpenCV.js API surface, so fighting the type
// checker over a binding that was never fully accurate isn't worthwhile;
// same tradeoff src/lib/pdfToImage.ts already makes for @napi-rs/canvas's
// DOMMatrix/ImageData/Path2D polyfills.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Cv = any;

let cvPromise: Promise<Cv> | null = null;

export function loadOpenCv(): Promise<Cv> {
  if (!cvPromise) {
    cvPromise = import("@techstark/opencv-js").then(
      (mod) =>
        new Promise<Cv>((resolve) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          const cvModule: any = (mod as any).default ?? mod;
          if (cvModule instanceof Promise) {
            cvModule.then(resolve);
          } else if (cvModule.Mat) {
            resolve(cvModule);
          } else {
            cvModule.onRuntimeInitialized = () => resolve(cvModule);
          }
        }),
    );
  }
  return cvPromise;
}
